pipeline:
  name: remote pipeline
  identifier: remote_pipeline
  projectIdentifier: michael_redman
  orgIdentifier: December_2023
  tags: {}
  stages:
    - stage:
        name: shell
        identifier: shell
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "this is a change in git"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
